### ISSUE TITLE
Student not found error thrown when student in course

### ISSUE THREAD

**Issue by edeitrick** [ksimuk/codio-api-examples#2]
I put myself in a course:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/6482570/171212135-1a5ed9f9-f6ec-4eb7-a518-f7e60cfc8f3e.png">

And when I try to give myself an extension, I get a student not found error:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/6482570/171211919-30b73f11-b95b-4beb-a60c-7ab1c5a98c22.png">

I am using a variation of: https://github.com/ksimuk/codio-api-examples/blob/master/src/covid-extension.ts

```
require('dotenv').config()
import codio from 'codio-api-js'
import { Assignment } from 'codio-api-js/lib/lib/course'
import _ from 'lodash'
const api = codio.v1

const clientId = process.env['CLIENT'] || 'clientId'
const secret = process.env['SECRET'] || 'secret'

// hardcoded values
const courseId = '78ac923e2db7cd49172bd102b8bfd4b2'
const studentEmail = 'edeitrick@codio.com'
let moduleName = ''
let assignmentNames = 'Introduction'
let shiftDays = 1
let shiftHours = 0
let shiftMinutes = 0

async function main() {
  await api.auth(clientId, secret)
  
  const assignments = _.compact(assignmentNames.split(','))
  const students = await api.course.getStudents(courseId)

  const student = _.find(students, {email: studentEmail})
  if (_.isUndefined(student)) {
      throw new Error(`${studentEmail} student not found`)
  }
  const course = await api.course.info(courseId)
  const toExtend: Assignment[] = []
  for (const module of course.modules) {
    if (module.name === moduleName) {
      toExtend.push.apply(module.assignments)
      continue
    }
    for (const assignment of module.assignments) {
      if (assignments.includes(assignment.name)) {
        toExtend.push(assignment)
      }
    }
  }

  const extend = shiftDays * 24 * 60 + shiftHours * 60 + shiftMinutes

  for(const assignment of toExtend) {
    console.log(`Extend ${assignment.name} for Student ${student.name} deadline on ${extend} minutes`)
    await api.assignment.updateStudentTimeExtension(courseId, assignment.id, student.id, {
        extendedDeadline: extend
    })
  }
}

main().catch(_ => {
  console.error(_);
  process.exit(1)
})
```

**Comment by ksimuk** [comment]
please add `console.log(students)` after `const students = ...` to see students that are being returned,

**Comment by edeitrick** [comment]
They don't seem to be:
>codio@suzukicritic-stellaarmor:~/workspace$ yarn start src/sliding-extension.ts
yarn run v1.22.19
$ ts-node  src/sliding-extension.ts
[]
Error: edeitrick@codio.com student not found
    at main (/home/codio/workspace/src/sliding-extension.ts:29:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by edeitrick** [comment]
But it's the same course id and API credentials from the print due dates script which works

**Comment by edeitrick** [comment]
Instructor's email and test student emails do NOT work
